### ISSUE TITLE
Error: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by olmokramer** [thomaslindstrom/color-picker#100]
Hey, I just updated to `v2.0.1` of color picker and everything seemed well (without restarting Atom). But now on Atom start I get this error:

```
Failed to activate the color-picker package
TypeError: Cannot read property 'add' of undefined
    at Object.module.exports.activate (/home/olmo/.atom/packages/color-picker/lib/ColorPicker.coffee:18:18)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:238:19)
    at /usr/share/atom/resources/app.asar/src/package.js:219:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:163:15)
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:211:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:435:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:419:29
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:414:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:395:46)
    at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom.js:636:21)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
```

**Comment by thomaslindstrom** [comment]
Weird. What version of `Atom` are you on?

**Comment by olmokramer** [comment]
I was on Atom 0.201.0. Just updated color-picker to 2.0.2 and everything seems to work just fine again... So thanks for the quick fix! :)
