### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by mrbernnz** [thomaslindstrom/color-picker#108]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.169.0
**System**: Mac OS X 10.10.3
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v1.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'type' of null

```
At /Users/BernzAir/.atom/packages/color-picker/lib/ColorPicker-view.coffee:383

TypeError: Cannot read property 'type' of null
  at ColorPickerView.module.exports.ColorPickerView.refreshColor (/Users/BernzAir/.atom/packages/color-picker/lib/ColorPicker-view.coffee:383:60)
  at HTMLBodyElement.<anonymous> (/Users/BernzAir/.atom/packages/color-picker/lib/ColorPicker-view.coffee:215:29)
  at HTMLBodyElement.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLBodyElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLBodyElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -2:42.8 command-palette:toggle (atom-text-editor.editor)
     -2:38.4 editor:consolidate-selections (atom-text-editor.editor.mini)
     -2:38.4 core:cancel (atom-text-editor.editor.mini)
     -2:30.0 tree-view:toggle (atom-text-editor.editor)
     -2:08.9 pane:split-down (atom-text-editor.editor)
  4x -2:05.8 click (div.close-icon)
     -1:49.1 pane:close (atom-text-editor.editor)
  2x -1:44.0 tree-view:toggle-focus (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
  4x -1:39.0 click (span.name.icon.icon-file-text)
     -0:55.6 window:toggle-full-screen (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:52.7 tool-panel:unfocus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:46.0 window:toggle-full-screen (atom-text-editor.editor)
     -0:29.9 window:run-package-specs (atom-text-editor.editor)
     -0:10.7 window:focus-pane-above (atom-text-editor.editor)
  3x -0:01.9 click (span.release-notes-status.icon.icon-squirrel.inline-block)
     -0:00.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-runner, v2.4.0
auto-update-packages, v0.2.2
autocomplete-paths, v1.0.2
autocomplete-plus, v2.1.3
autocomplete-snippets, v1.0.1
color-picker, v1.7.0
linter, v0.10.1
select-line, v0.16.0
seti-syntax, v0.2.1
seti-ui, v0.7.1
trailing-spaces, v0.3.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by thomaslindstrom** [comment]
Hi, @mrbernnz, please update both Atom and `color-picker`, and this issue will be fixed.
