### ISSUE TITLE
Uncaught TypeError: Cannot read property 'height' of undefined

### ISSUE THREAD

**Issue by makingoff** [thomaslindstrom/color-picker#115]
[Enter steps to reproduce below:]

1. Just updated for 0.210.0

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.4
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v2.0.5

### Stack Trace

Uncaught TypeError: Cannot read property 'height' of undefined

```
At /Users/makingoff/.atom/packages/color-picker/lib/extensions/Alpha.coffee:147

TypeError: Cannot read property 'height' of undefined
  at Object._this.control.setSelection (/Users/makingoff/.atom/packages/color-picker/lib/extensions/Alpha.coffee:147:39)
  at /Users/makingoff/.atom/packages/color-picker/lib/extensions/Alpha.coffee:181:30
  at Object.emit (/Users/makingoff/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
  at Object.emitInputColor (/Users/makingoff/.atom/packages/color-picker/lib/ColorPicker-view.coffee:232:22)
  at Object.open (/Users/makingoff/.atom/packages/color-picker/lib/ColorPicker-view.coffee:309:23)
  at atom-text-editor.<anonymous> (/Users/makingoff/.atom/packages/color-picker/lib/ColorPicker.coffee:42:68)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -1:01.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:01.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  3x -1:01.0 core:move-left (atom-text-editor.editor.is-focused)
  5x -0:59.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:58.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:58.2.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:57.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:38.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:38.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:37.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:37.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:36.2.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -0:35.3.0 core:undo (atom-text-editor.editor.is-focused)
     -0:34.9.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -0:32.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.0 color-picker:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autosave",
      "welcome",
      "minimap",
      "atom-color-highlight",
      "select-line"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "projectHome": "/Users/makingoff/Dropbox/projects",
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.0
atom-pair, v1.1.6
color-picker, v2.0.5
emmet, v2.3.10
gulp-control, v0.4.2
hotkeys, v0.0.0
language-slim, v0.4.0
language-twig, v1.6.1
pane-split-moves-tab, v0.0.1
space-tab, v0.4.2
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by thomaslindstrom** [comment]
Hi, @makingoff. Is this bug still present?

**Comment by makingoff** [comment]
Sorry, @thomaslindstrom. My answer so late. Everything fine with `height`.
