### ISSUE TITLE
Uncaught TypeError: Cannot read property 'shadowRoot' of undefined

### ISSUE THREAD

**Issue by andersonmadeira** [thomaslindstrom/color-picker#116]
[Enter steps to reproduce below:]

1. Just installed Atom
2. Then pressed CTRL+ALT+C
3. Then... BOOM. '-'

**Atom Version**: 0.210.0
**System**: Ubuntu 14.04.2
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v2.0.6

### Stack Trace

Uncaught TypeError: Cannot read property 'shadowRoot' of undefined

```
At /home/~/.atom/packages/color-picker/lib/ColorPicker-view.coffee:257

TypeError: Cannot read property 'shadowRoot' of undefined
  at Object.open (/home/desenvolvimento/.atom/packages/color-picker/lib/ColorPicker-view.coffee:257:36)
  at atom-text-editor.<anonymous> (/home/desenvolvimento/.atom/packages/color-picker/lib/ColorPicker.coffee:42:68)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
  4x -9:35.8.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -9:28 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -9:27.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
  2x -9:26.6.0 core:undo (atom-text-editor.editor.is-focused)
  2x -8:31.1.0 core:backspace (atom-text-editor#editor.fontSize.editor.mini.is-focused)
     -8:18.7.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -8:17.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:14.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -8:13.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -8:13.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:12.7.0 core:save (atom-text-editor.editor.is-focused)
  9x -2:07.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.8.0 color-picker:open (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.6

# Dev
No dev packages
```

**Comment by andersonmadeira** [comment]
So, the plugin is supposed to be used in the editor window, right? Sorry for the dumb bug report. You may close (delete) this issue. Thanks.

**Comment by thomaslindstrom** [comment]
Hm.. But where did you try using it, @andersonmadeira?
