### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by fnkr** [thomaslindstrom/color-picker#121]
Steps to reproduce:

1. Install the [git-log](https://atom.io/packages/git-log) and color-picker packages
2. Open the git log window
3. Try to close it -> color-picker throws an error and the tab doesnt close

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v2.0.7

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At C:\Users\Florian\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:25

TypeError: Cannot read property 'dispose' of undefined
  at C:\Users\Florian\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:25:28
  at Set.forEach (native)
  at CompositeDisposable.module.exports.CompositeDisposable.dispose (C:\Users\Florian\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:24:26)
  at tabs-tab.module.exports.TabView.destroy (C:\Users\Florian\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\tabs\lib\tab-view.js:194:14)
  at TabBarView.module.exports.TabBarView.removeTabForItem (C:\Users\Florian\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:364:15)
  at C:\Users\Florian\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:174:24
  at Emitter.module.exports.Emitter.emit (C:\Users\Florian\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.removeItem (C:\Users\Florian\AppData\Local\atom\app-1.0.0\resources\app.asar\src\pane.js:379:20)
  at Pane.module.exports.Pane.destroyItem (C:\Users\Florian\AppData\Local\atom\app-1.0.0\resources\app.asar\src\pane.js:442:16)
  at Pane.module.exports.Pane.destroyActiveItem (C:\Users\Florian\AppData\Local\atom\app-1.0.0\resources\app.asar\src\pane.js:419:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (C:\Users\Florian\AppData\Local\atom\app-1.0.0\resources\app.asar\src\workspace.js:600:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (C:\Users\Florian\AppData\Local\atom\app-1.0.0\resources\app.asar\src\workspace.js:639:21)
  at atom-workspace.atom.commands.add.core:close (C:\Users\Florian\AppData\Local\atom\app-1.0.0\resources\app.asar\src\workspace-element.js:308:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Florian\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\Florian\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Florian\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Florian\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Florian\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:180:20)

```

### Commands

```
     -0:07.2.0 git-log:show (atom-text-editor.editor.is-focused)
     -0:05.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Installed Packages

```coffee
# User
color-picker, v2.0.7
git-log, v0.4.1
```

**Comment by thomaslindstrom** [comment]
It seems this might not be an issue with `color-picker`, but rather a bug in the `tabs` package. https://github.com/atom/tabs/issues/183
