### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.

### ISSUE THREAD

**Issue by sammartinez** [thomaslindstrom/color-picker#136]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.4
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v2.0.11

### Stack Trace

Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.

```
At /Users/Guest/.atom/packages/color-picker/lib/extensions/Alpha.coffee:103

Error: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.
  at Error (native)
  at Object._this.canvas.render (/Users/Guest/.atom/packages/color-picker/lib/extensions/Alpha.coffee:103:35)
  at /Users/Guest/.atom/packages/color-picker/lib/extensions/Alpha.coffee:112:29
  at Object.emit (/Users/Guest/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
  at Object.emitColorChanged (/Users/Guest/.atom/packages/color-picker/lib/extensions/Saturation.coffee:24:22)
  at /Users/Guest/.atom/packages/color-picker/lib/extensions/Saturation.coffee:211:61
  at Object.emit (/Users/Guest/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
  at Object.emitSelectionChanged (/Users/Guest/.atom/packages/color-picker/lib/extensions/Saturation.coffee:18:22)
  at Object._this.control.setSelection (/Users/Guest/.atom/packages/color-picker/lib/extensions/Saturation.coffee:200:43)
  at /Users/Guest/.atom/packages/color-picker/lib/extensions/Saturation.coffee:208:30
  at Object.emit (/Users/Guest/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
  at Object.emitInputColor (/Users/Guest/.atom/packages/color-picker/lib/ColorPicker-view.coffee:233:22)
  at Object.open (/Users/Guest/.atom/packages/color-picker/lib/ColorPicker-view.coffee:314:23)
  at atom-text-editor.<anonymous> (/Users/Guest/.atom/packages/color-picker/lib/ColorPicker.coffee:42:68)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:70:67)
  at EventEmitter.emit (events.js:119:17)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:141:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -7:09.3 core:move-left (atom-text-editor.editor)
  2x -7:09.0 core:backspace (atom-text-editor.editor)
     -7:06.2 core:save (atom-text-editor.editor)
 13x -6:32.7 core:backspace (atom-text-editor.editor)
     -5:29.4 core:save (atom-text-editor.editor)
  2x -5:20.3 core:backspace (atom-text-editor.editor)
     -5:16.1 core:save (atom-text-editor.editor)
  6x -4:35.8 core:backspace (atom-text-editor.editor)
  2x -4:30.5 editor:newline (atom-text-editor.editor)
     -4:25.8 core:backspace (atom-text-editor.editor)
     -4:22.1 core:move-right (atom-text-editor.editor)
     -4:20.8 core:save (atom-text-editor.editor)
  4x -4:16.7 core:backspace (atom-text-editor.editor)
     -4:08.5 core:save (atom-text-editor.editor)
     -3:53.2 editor:newline (atom-text-editor.editor)
  2x -2:45.6 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "batman-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
batman-syntax, v1.0.0
color-picker, v2.0.11

# Dev
No dev packages
```

/cc @atom/core

**Comment by thomaslindstrom** [comment]
Please try installing a newer version and try again. If that doesn't work, please report back in issue #114.
