### ISSUE TITLE
Uncaught TypeError: _selection.marker.getPixelRange is not a function

### ISSUE THREAD

**Issue by pkpowell** [thomaslindstrom/color-picker#141]
[Enter steps to reproduce below:]

1. open color-picker (command-shift-c)

**Atom Version**: 1.2.0-dev-e9a8646
**System**: Mac OS X 10.11
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v2.0.12

### Stack Trace

Uncaught TypeError: _selection.marker.getPixelRange is not a function

```
At /Users/phil/.atom/packages/color-picker/lib/ColorPicker-view.coffee:386

TypeError: _selection.marker.getPixelRange is not a function
  at Object.open (/Users/phil/.atom/packages/color-picker/lib/ColorPicker-view.coffee:360:56)
  at atom-text-editor.<anonymous> (/Users/phil/.atom/packages/color-picker/lib/ColorPicker.coffee:42:68)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:95:20)

```

### Commands

```
     -1:41.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:37.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:37.4.0 sync-settings:backup (atom-text-editor.editor)
     -1:02.2.0 color-picker:open (atom-text-editor.editor.is-focused)
     -0:30.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:30.4.0 git-diff-details:close-git-diff-details (atom-text-editor.editor.is-focused)
     -0:30.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:22.6.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -0:01.7.0 color-picker:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "minimap",
      "linter-puppet-lint",
      "travis-ci-status",
      "jsformat",
      "esformatter",
      "emmet",
      "jshint",
      "emmet-simplified",
      "atom-terminal-panel",
      "atom-terminal",
      "remote-atom",
      "atom-beautify"
    ],
    "projectHome": "~/devstuff"
  }
}
```

### Installed Packages

```coffee
# User
api-docs, v0.0.3
color-picker, v2.0.12
file-icons, v1.6.9
git-diff-details, v0.20.0
language-puppet, v0.14.0
linter, v1.7.2
linter-jshint, v1.2.1
meteor-api, v2.20.0
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by thomaslindstrom** [comment]
This is fixed in `v2.0.13`. Thanks!
