### ISSUE TITLE
Uncaught TypeError: deprecationSite.getFileName is not a function

### ISSUE THREAD

**Issue by ImAtome** [thomaslindstrom/color-picker#149]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.2
**System**: Mac OS X 10.11.1
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v2.0.13

### Stack Trace

Uncaught TypeError: deprecationSite.getFileName is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/grim/lib/grim.js:56

TypeError: deprecationSite.getFileName is not a function
  at Object.global.__grim__.deprecate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/grim/lib/grim.js:56:36)
  at TextEditor.module.exports.TextEditor.getVisibleRowRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2914:12)
  at Object.open (/Users/JulienL/.atom/packages/color-picker/lib/ColorPicker-view.coffee:270:39)
  at atom-text-editor.<anonymous> (/Users/JulienL/.atom/packages/color-picker/lib/ColorPicker.coffee:42:68)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
  at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:993:28)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:138:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:156:33)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:252:47)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

```

### Commands

```
     -4:15.4.0 core:save (atom-text-editor.editor.is-focused)
     -4:07.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:04.8.0 core:save (atom-text-editor.editor.is-focused)
     -4:02.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:01.0 core:save (atom-text-editor.editor.is-focused)
     -3:53.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:53.1.0 core:save (atom-text-editor.editor.is-focused)
     -3:04.5.0 core:copy (atom-text-editor.editor.is-focused)
     -2:55.5.0 core:paste (atom-text-editor.editor.is-focused)
     -2:53.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:52.1.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:52 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:52 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -2:51 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:50.8.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -0:48.4.0 color-picker:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.13
file-icons, v1.6.11
language-babel, v2.5.0
nuclide-flow, v0.0.32
seti-syntax, v0.4.1
seti-ui, v0.8.1

# Dev
No dev packages
```

**Comment by thomaslindstrom** [comment]
This looks like it's not directly related to `color-picker`. Is this still happening?

**Comment by ImAtome** [comment]
No it's fixed, I think that was the Atom's version .

**Comment by thomaslindstrom** [comment]
Ok!
