### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by monlone** [thomaslindstrom/color-picker#158]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Unknown Windows Version
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v2.0.14

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At D:\Atom\resources\app.asar\node_modules\fuzzaldrin\lib\filter.js:19

TypeError: Cannot read property 'length' of undefined
    at module.exports (D:\Atom\resources\app.asar\node_modules\fuzzaldrin\lib\filter.js:19:37)
    at Object.module.exports.filter (D:\Atom\resources\app.asar\node_modules\fuzzaldrin\lib\fuzzaldrin.js:21:14)
    at ClassProvider.module.exports.ClassProvider.gotoFromWord (file:///C:/Users/shaohua/.atom/packages/atom-autocomplete-php/lib/goto/class-provider.coffee:30:31)
    at HTMLSpanElement.<anonymous> (file:///C:/Users/shaohua/.atom/packages/atom-autocomplete-php/lib/goto/abstract-provider.coffee:133:22)
    at HTMLDivElement.jQuery.event.dispatch (D:\Atom\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (D:\Atom\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -8:03.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:54.7.0 symbols-view:go-to-declaration (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:23 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:04.2.0 symbols-view:toggle-project-symbols (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.1
autocomplete-php, v0.3.7
color-picker, v2.0.14
minimap, v4.18.2
php-cs-fixer, v2.5.1
php-debug, v0.1.4
pigments, v0.19.3
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by thomaslindstrom** [comment]
This looks like a bug unrelated to `color-picker`.

**Comment by monlone** [comment]
ok,thank u!
