### ISSUE TITLE
Ctrl-Alt-C when Color Picker is Disabled

### ISSUE THREAD

**Issue by SoCalDude** [thomaslindstrom/color-picker#161]
[Enter steps to reproduce below:]

1. Disable (do not uninstall) Color Picker
2. When editing a document, perform a Ctrl-Alt-C.

**Atom Version**: 1.4.0
**System**: Microsoft Windows 8.1
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v2.0.14

### Stack Trace

Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.

```
At /C:/Users/J.Les/.atom/packages/color-picker/lib/extensions/Alpha.coffee:93

Error: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.
    at Error (native)
    at Object._this.canvas.render (file:///C:/Users/J.Les/.atom/packages/color-picker/lib/extensions/Alpha.coffee:103:35)
    at file:///C:/Users/J.Les/.atom/packages/color-picker/lib/extensions/Alpha.coffee:112:29
    at Object.emit (file:///C:/Users/J.Les/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitColorChanged (file:///C:/Users/J.Les/.atom/packages/color-picker/lib/extensions/Saturation.coffee:24:22)
    at file:///C:/Users/J.Les/.atom/packages/color-picker/lib/extensions/Saturation.coffee:211:61
    at Object.emit (file:///C:/Users/J.Les/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitSelectionChanged (file:///C:/Users/J.Les/.atom/packages/color-picker/lib/extensions/Saturation.coffee:18:22)
    at Object._this.control.setSelection (file:///C:/Users/J.Les/.atom/packages/color-picker/lib/extensions/Saturation.coffee:200:43)
    at file:///C:/Users/J.Les/.atom/packages/color-picker/lib/extensions/Saturation.coffee:208:30
    at Object.emit (file:///C:/Users/J.Les/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitInputColor (file:///C:/Users/J.Les/.atom/packages/color-picker/lib/ColorPicker-view.coffee:234:22)
    at Object.open (file:///C:/Users/J.Les/.atom/packages/color-picker/lib/ColorPicker-view.coffee:328:18)
    at atom-text-editor.<anonymous> (file:///C:/Users/J.Les/.atom/packages/color-picker/lib/ColorPicker.coffee:42:68)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\J.Les\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\J.Les\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\J.Les\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\J.Les\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\J.Les\AppData\Local\atom\app-1.4.0\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\J.Les\AppData\Local\atom\app-1.4.0\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
  3x -5:40.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:36.2.0 color-picker:open (atom-text-editor.editor.is-focused)
     -3:46.3.0 core:save (atom-text-editor.editor.is-focused)
     -3:01.3.0 color-picker:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "line-ending-converter",
      "color-picker"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
column-select, v0.2.0
hex, v0.6.2
highlight-line, v0.11.0
highlight-selected, v0.11.1
language-batch, v0.3.3
open-recent, v4.0.1
pigments, v0.19.6

# Dev
No dev packages
```

**Comment by thomaslindstrom** [comment]
Please update `color-picker` to `v2.1.1` and **restart Atom**. This should be fixed now!
