### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.

### ISSUE THREAD

**Issue by anandvip** [thomaslindstrom/color-picker#166]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.10.5
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v2.1.0

### Stack Trace

Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.

```
At /Users/vipul/.atom/packages/color-picker/lib/extensions/Alpha.coffee:103

Error: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.
    at Error (native)
    at Object._this.canvas.render (/Users/vipul/.atom/packages/color-picker/lib/extensions/Alpha.coffee:103:35)
    at /Users/vipul/.atom/packages/color-picker/lib/extensions/Alpha.coffee:112:29
    at Object.emit (/Users/vipul/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitColorChanged (/Users/vipul/.atom/packages/color-picker/lib/extensions/Saturation.coffee:24:22)
    at /Users/vipul/.atom/packages/color-picker/lib/extensions/Saturation.coffee:211:61
    at Object.emit (/Users/vipul/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitSelectionChanged (/Users/vipul/.atom/packages/color-picker/lib/extensions/Saturation.coffee:18:22)
    at Object._this.control.setSelection (/Users/vipul/.atom/packages/color-picker/lib/extensions/Saturation.coffee:200:43)
    at /Users/vipul/.atom/packages/color-picker/lib/extensions/Saturation.coffee:208:30
    at Object.emit (/Users/vipul/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitInputColor (/Users/vipul/.atom/packages/color-picker/lib/ColorPicker-view.coffee:234:22)
    at Object.open (/Users/vipul/.atom/packages/color-picker/lib/ColorPicker-view.coffee:311:32)
    at atom-text-editor.<anonymous> (/Users/vipul/.atom/packages/color-picker/lib/ColorPicker.coffee:42:68)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -5:17.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:17.4.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:15.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:15.2.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -5:13.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:52.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:50 core:backspace (atom-text-editor.editor.is-focused)
     -4:47.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:47.9.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:40.5.0 core:cut (atom-text-editor.editor.is-focused)
     -4:37.7.0 core:paste (atom-text-editor.editor.is-focused)
     -4:15.4.0 core:save (atom-text-editor.editor.is-focused)
  5x -4:08.3.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -3:43 color-picker:open (atom-text-editor.editor.is-focused)
     -0:14.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.0 color-picker:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-control"
    ],
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ]
  },
  "color-picker": {
    "triggerKey": "K"
  }
}
```

### Installed Packages

```coffee
# User
antialiased, v0.1.0
atom-beautify, v0.28.21
atom-html-preview, v0.1.13
atom-jshint, v2.0.0
atom-material-ui, v0.8.0
atom-wrap-in-tag, v0.5.0
autoclose-html, v0.19.0
autocomplete-angular-material, v0.4.0
browser-plus, v0.0.54
color-picker, v2.1.0
css-snippets, v0.9.0
file-icons, v1.6.14
git-plus, v5.12.0
js-refactor, v0.6.0
linter, v1.11.3
linter-eslint, v5.2.7
linter-htmlhint, v1.0.0
minimap, v4.19.0
minimap-bookmarks, v0.2.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-hide, v0.3.0
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.1
open-in-browser, v0.4.6
open-in-browsers, v0.0.7
pigments, v0.20.0
preview-plus, v1.2.6
regex-tester, v0.2.0

# Dev
No dev packages
```

**Comment by thomaslindstrom** [comment]
Please update `color-picker` to `v2.1.1` and **restart Atom**. This should be fixed now!
