### ISSUE TITLE
color picking

### ISSUE THREAD

**Issue by bipinchandra000** [thomaslindstrom/color-picker#167]
/C:/Users/Bipin/.atom/packages/color-picker/lib/extensions/Alpha.coffee:93
Hide Stack Trace
Error: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.
    at Error (native)
    at Object._this.canvas.render (file:///C:/Users/Bipin/.atom/packages/color-picker/lib/extensions/Alpha.coffee:103:35)
    at file:///C:/Users/Bipin/.atom/packages/color-picker/lib/extensions/Alpha.coffee:112:29
    at Object.emit (file:///C:/Users/Bipin/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitColorChanged (file:///C:/Users/Bipin/.atom/packages/color-picker/lib/extensions/Saturation.coffee:24:22)
    at file:///C:/Users/Bipin/.atom/packages/color-picker/lib/extensions/Saturation.coffee:211:61
    at Object.emit (file:///C:/Users/Bipin/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitSelectionChanged (file:///C:/Users/Bipin/.atom/packages/color-picker/lib/extensions/Saturation.coffee:18:22)
    at Object._this.control.setSelection (file:///C:/Users/Bipin/.atom/packages/color-picker/lib/extensions/Saturation.coffee:200:43)
    at file:///C:/Users/Bipin/.atom/packages/color-picker/lib/extensions/Saturation.coffee:208:30
    at Object.emit (file:///C:/Users/Bipin/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitInputColor (file:///C:/Users/Bipin/.atom/packages/color-picker/lib/ColorPicker-view.coffee:234:22)
    at Object.open (file:///C:/Users/Bipin/.atom/packages/color-picker/lib/ColorPicker-view.coffee:309:29)
    at atom-text-editor.<anonymous> (file:///C:/Users/Bipin/.atom/packages/color-picker/lib/ColorPicker.coffee:42:68)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Bipin\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Bipin\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Bipin\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Bipin\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\Bipin\AppData\Local\atom\app-1.4.0\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\Bipin\AppData\Local\atom\app-1.4.0\resources\app.asar\src\window-event-handler.js:3:61)

**Comment by thomaslindstrom** [comment]
Please update `color-picker` to `v2.1.1` and **restart Atom**. This should be fixed now!
