### ISSUE TITLE
Failed to execute 'addColorStop' on 'CanvasGradient':

### ISSUE THREAD

**Issue by rayhanprima99** [thomaslindstrom/color-picker#171]
Error: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('hsl(NaN,100%,50%)') could not be parsed as a color.
    at Error (native)
    at Object._this.canvas.render (file:///C:/Users/Rayhan/.atom/packages/color-picker/lib/extensions/Saturation.coffee:113:35)
    at file:///C:/Users/Rayhan/.atom/packages/color-picker/lib/extensions/Saturation.coffee:129:29
    at Object.emit (file:///C:/Users/Rayhan/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitColorChanged (file:///C:/Users/Rayhan/.atom/packages/color-picker/lib/extensions/Hue.coffee:32:22)
    at file:///C:/Users/Rayhan/.atom/packages/color-picker/lib/extensions/Hue.coffee:176:47
    at Object.emit (file:///C:/Users/Rayhan/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitSelectionChanged (file:///C:/Users/Rayhan/.atom/packages/color-picker/lib/extensions/Hue.coffee:26:22)
    at Object._this.control.setSelection (file:///C:/Users/Rayhan/.atom/packages/color-picker/lib/extensions/Hue.coffee:165:36)
    at file:///C:/Users/Rayhan/.atom/packages/color-picker/lib/extensions/Hue.coffee:173:30
    at Object.emit (file:///C:/Users/Rayhan/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitInputColor (file:///C:/Users/Rayhan/.atom/packages/color-picker/lib/ColorPicker-view.coffee:234:22)
    at Object.open (file:///C:/Users/Rayhan/.atom/packages/color-picker/lib/ColorPicker-view.coffee:328:18)
    at atom-text-editor.<anonymous> (file:///C:/Users/Rayhan/.atom/packages/color-picker/lib/ColorPicker.coffee:42:68)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Rayhan\AppData\Local\atom\app-1.4.3\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Rayhan\AppData\Local\atom\app-1.4.3\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Rayhan\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Rayhan\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\Rayhan\AppData\Local\atom\app-1.4.3\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\Rayhan\AppData\Local\atom\app-1.4.3\resources\app.asar\src\window-event-handler.js:3:61)

**Comment by thomaslindstrom** [comment]
Please update `color-picker` and restart Atom.
