### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.

### ISSUE THREAD

**Issue by BryanHerrera09** [thomaslindstrom/color-picker#178]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Unknown Windows Version
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v2.1.1

### Stack Trace

Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.

```
At C:\Users\user\.atom\packages\color-picker\lib\extensions\Alpha.coffee:93

Error: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.
    at Error (native)
    at Object._this.canvas.render (C:\Users\user\.atom\packages\color-picker\lib\extensions\Alpha.coffee:93:27)
    at C:\Users\user\.atom\packages\color-picker\lib\extensions\Alpha.coffee:101:35
    at Object.emit (C:\Users\user\.atom\packages\color-picker\lib\modules\Emitter.coffee:15:21)
    at Object.emitColorChanged (C:\Users\user\.atom\packages\color-picker\lib\extensions\Saturation.coffee:15:29)
    at C:\Users\user\.atom\packages\color-picker\lib\extensions\Saturation.coffee:212:33
    at Object.emit (C:\Users\user\.atom\packages\color-picker\lib\modules\Emitter.coffee:15:21)
    at Object.emitSelectionChanged (C:\Users\user\.atom\packages\color-picker\lib\extensions\Saturation.coffee:9:29)
    at Object._this.control.setSelection (C:\Users\user\.atom\packages\color-picker\lib\extensions\Saturation.coffee:199:35)
    at C:\Users\user\.atom\packages\color-picker\lib\extensions\Saturation.coffee:209:36
    at Object.emit (C:\Users\user\.atom\packages\color-picker\lib\modules\Emitter.coffee:15:21)
    at Object.emitInputColor (C:\Users\user\.atom\packages\color-picker\lib\ColorPicker-view.coffee:233:22)
    at Object.open (C:\Users\user\.atom\packages\color-picker\lib\ColorPicker-view.coffee:314:23)
    at atom-text-editor.<anonymous> (C:\Users\user\.atom\packages\color-picker\lib\ColorPicker.coffee:31:53)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\user\AppData\Local\atom\app-1.5.4\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\user\AppData\Local\atom\app-1.5.4\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\user\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\user\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\user\AppData\Local\atom\app-1.5.4\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\user\AppData\Local\atom\app-1.5.4\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -6:14.1.0 color-picker:open (atom-text-editor.editor.is-focused)
  2x -5:48.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:29.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:29.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:06.1.0 editor:copy-path (atom-text-editor.editor.is-focused)
     -0:04.8.0 color-picker:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "color-picker"
    ],
    "themes": [
      "one-dark-ui",
      "an-old-hope-syntax"
    ]
  },
  "color-picker": {
    "abbreviateValues": true,
    "automaticReplace": true,
    "uppercaseColorValues": true
  }
}
```

### Installed Packages

```coffee
# User
an-old-hope-syntax, v0.5.0
emmet, v2.3.15
file-icons, v1.6.18
linter, v1.11.3
minimap, v4.16.2
pigments, v0.24.2

# Dev
No dev packages
```

**Comment by thomaslindstrom** [comment]
Please restart Atom and try again.
