### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.

### ISSUE THREAD

**Issue by khaleelsyed** [thomaslindstrom/color-picker#187]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Home Single Language
**Thrown From**: [color-picker-master](https://github.com/thomaslindstrom/color-picker) package, vundefined

### Stack Trace

Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.

```
At /C:/Users/Admin/.atom/packages/color-picker-master/lib/extensions/Alpha.coffee:93

Error: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.
    at Error (native)
    at Object._this.canvas.render (file:///C:/Users/Admin/.atom/packages/color-picker-master/lib/extensions/Alpha.coffee:103:35)
    at file:///C:/Users/Admin/.atom/packages/color-picker-master/lib/extensions/Alpha.coffee:112:29
    at Object.emit (file:///C:/Users/Admin/.atom/packages/color-picker-master/lib/modules/Emitter.coffee:11:23)
    at Object.emitColorChanged (file:///C:/Users/Admin/.atom/packages/color-picker-master/lib/extensions/Saturation.coffee:24:22)
    at file:///C:/Users/Admin/.atom/packages/color-picker-master/lib/extensions/Saturation.coffee:211:61
    at Object.emit (file:///C:/Users/Admin/.atom/packages/color-picker-master/lib/modules/Emitter.coffee:11:23)
    at Object.emitSelectionChanged (file:///C:/Users/Admin/.atom/packages/color-picker-master/lib/extensions/Saturation.coffee:18:22)
    at Object._this.control.setSelection (file:///C:/Users/Admin/.atom/packages/color-picker-master/lib/extensions/Saturation.coffee:200:43)
    at file:///C:/Users/Admin/.atom/packages/color-picker-master/lib/extensions/Saturation.coffee:208:30
    at Object.emit (file:///C:/Users/Admin/.atom/packages/color-picker-master/lib/modules/Emitter.coffee:11:23)
    at Object.emitInputColor (file:///C:/Users/Admin/.atom/packages/color-picker-master/lib/ColorPicker-view.coffee:237:22)
    at Object.open (file:///C:/Users/Admin/.atom/packages/color-picker-master/lib/ColorPicker-view.coffee:318:23)
    at atom-text-editor.<anonymous> (file:///C:/Users/Admin/.atom/packages/color-picker-master/lib/ColorPicker.coffee:47:23)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\Admin\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -3:59.5.0 editor:newline (atom-text-editor.editor.is-focused.power-mode)
  4x -3:57.3.0 core:backspace (atom-text-editor.editor.is-focused.power-mode)
     -3:55.3.0 activate-power-mode:toggle (atom-text-editor.editor.is-focused.power-mode)
  5x -3:54 core:backspace (atom-text-editor.editor.is-focused.power-mode.autocomplete-active)
     -3:47 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused.power-mode)
 16x -3:46.8.0 core:backspace (atom-text-editor.editor.is-focused.power-mode)
     -2:22.1.0 editor:select-to-beginning-of-word (atom-text-editor.editor.power-mode.is-focused)
 15x -2:21.6.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
 18x -1:44.4.0 editor:select-to-beginning-of-word (atom-text-editor.editor.power-mode.is-focused)
  2x -1:40.7.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -1:26.2.0 editor:select-to-beginning-of-word (atom-text-editor.editor.power-mode.is-focused)
     -1:26 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -1:06.8.0 editor:select-to-beginning-of-word (atom-text-editor.editor.power-mode.is-focused)
     -1:06.5.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -1:00.1.0 core:save (atom-text-editor.editor.power-mode.is-focused)
  6x -0:39.4.0 color-picker:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
minimap, v4.24.4

# Dev
No dev packages
```

**Comment by thomaslindstrom** [comment]
Please update Atom and `color-picker`, and try again.
