### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.

### ISSUE THREAD

**Issue by denniskim11** [thomaslindstrom/color-picker#189]
.atom/packages/color-picker/lib/extensions/Alpha.coffee:103
Hide Stack Trace
Error: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(NaN,NaN,NaN,1)') could not be parsed as a color.
    at Error (native)
    at Object._this.canvas.render (/Users/denniskim/.atom/packages/color-picker/lib/extensions/Alpha.coffee:103:35)
    at /Users/denniskim/.atom/packages/color-picker/lib/extensions/Alpha.coffee:112:29
    at Object.emit (/Users/denniskim/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitColorChanged (/Users/denniskim/.atom/packages/color-picker/lib/extensions/Saturation.coffee:24:22)
    at /Users/denniskim/.atom/packages/color-picker/lib/extensions/Saturation.coffee:211:61
    at Object.emit (/Users/denniskim/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitSelectionChanged (/Users/denniskim/.atom/packages/color-picker/lib/extensions/Saturation.coffee:18:22)
    at Object._this.control.setSelection (/Users/denniskim/.atom/packages/color-picker/lib/extensions/Saturation.coffee:200:43)
    at /Users/denniskim/.atom/packages/color-picker/lib/extensions/Saturation.coffee:208:30
    at Object.emit (/Users/denniskim/.atom/packages/color-picker/lib/modules/Emitter.coffee:11:23)
    at Object.emitInputColor (/Users/denniskim/.atom/packages/color-picker/lib/ColorPicker-view.coffee:237:22)
    at Object.open (/Users/denniskim/.atom/packages/color-picker/lib/ColorPicker-view.coffee:318:23)
    at atom-text-editor.<anonymous> (/Users/denniskim/.atom/packages/color-picker/lib/ColorPicker.coffee:47:23)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

so I read a couple of other posts that had the same issues, and I guess the simple fix for them was installing the most update version. So I reinstalled the package and it worked once and it stopped working. can the error be from the recent update?

**Comment by Rawnly** [comment]
i have the same issue, i've risolved installing the previus release manually, but i'm waiting for a bugfix

**Comment by thomaslindstrom** [comment]
Sorry, guys. I've published `v2.2.1` now that should work.

**Comment by denniskkim** [comment]
sweet thanks man!
