### ISSUE TITLE
TypeError: Cannot read property 'offsetLeft' of null

### ISSUE THREAD

**Issue by Jinnial** [thomaslindstrom/color-picker#211]
Just got this error when I run the packaged from the right click menu.

``` TypeError: Cannot read property 'offsetLeft' of null
    at Object.open (file:///C:/Users/reevesb/.atom/packages/color-picker/lib/ColorPicker-view.coffee:355:73)
    at atom-text-editor.<anonymous> (file:///C:/Users/reevesb/.atom/packages/color-picker/lib/ColorPicker.coffee:47:23)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Program Files (x86)\Atom\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Program Files (x86)\Atom\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Program Files (x86)\Atom\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Program Files (x86)\Atom\resources\app.asar\src\atom-environment.js:1115:28)
    at EventEmitter.outerCallback (C:\Program Files (x86)\Atom\resources\app.asar\src\application-delegate.js:342:25)
    at emitThree (events.js:110:13)
    at EventEmitter.emit (events.js:188:7)```

**Comment by HELSIS666** [comment]
+1

**Comment by m-artin** [comment]
+1

Always get the same error, also after pressing cmd-shift-c

**Comment by paceUlibDev** [comment]
+1

**Comment by m-artin** [comment]
Thanks @paceUlibDev. Updating Atom did the trick.

**Comment by ahgomes** [comment]
+1
