### ISSUE TITLE
Uncaught TypeError: Cursor.getPixelRect is not a function

### ISSUE THREAD

**Issue by huysh3** [thomaslindstrom/color-picker#213]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.2
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package 2.2.2

### Stack Trace

Uncaught TypeError: Cursor.getPixelRect is not a function

```
At /Users/Ni_hen/.atom/packages/color-picker/lib/ColorPicker-view.coffee:365

TypeError: Cursor.getPixelRect is not a function
    at Object.open (/packages/color-picker/lib/ColorPicker-view.coffee:365:42)
    at /packages/color-picker/lib/ColorPicker.coffee:47:23)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -4:52.5.0 editor:newline (input.hidden-input)
  4x -4:49.3.0 core:backspace (input.hidden-input)
     -4:45.4.0 editor:newline (input.hidden-input)
     -4:42.9.0 autocomplete-plus:confirm (input.hidden-input)
     -4:42.9.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  5x -4:37.6.0 core:backspace (input.hidden-input)
     -4:32.5.0 core:move-left (input.hidden-input)
     -4:32.1.0 find-and-replace:select-next (input.hidden-input)
  2x -4:31.5.0 color-picker:open (input.hidden-input)
     -4:15.5.0 core:save (input.hidden-input)
     -4:13.9.0 settings-view:open (input.hidden-input)
  4x -3:52.7.0 color-picker:open (input.hidden-input)
     -1:01.9.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:49.3.0 pane:show-previous-recently-used-item (a.btn-issue.btn.btn-error)
     -0:48.2.0 pane:show-next-recently-used-item (a.btn-issue.btn.btn-error)
     -0:14.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.29.13 
atom-clock 0.1.2 
atom-html-preview 0.1.22 
atom-material-syntax 0.4.5 
atom-ternjs 0.15.0 
atom-wx 0.1.1 
autocomplete-html-entities 0.1.0 
autocomplete-paths 1.0.2 
autoprefixer 3.3.0 
color-picker 2.2.2 
css-snippets 1.1.0 
dark-flat-ui 1.2.4 
duotone-dark-syntax 1.0.0 
emmet 2.4.3 
ex-mode 0.13.0 
expose 0.12.1 
file-icons 1.7.24 
genesis-ui 0.5.0 
git-plus 5.23.2 
git-time-machine 1.5.3 
highlight-selected 0.11.2 
hyperclick 0.0.39 
js-hyperclick 1.9.0 
language-babel 2.37.0 
language-javascript-jsx 0.3.7 
language-jsx 0.1.1 
language-vue 0.20.0 
language-vue-component 0.5.0 
linter 1.11.10 
linter-js-standard 3.3.3 
oceanic-next 0.4.0 
pigments 0.37.0 
react 0.16.0 
react-snippets 0.4.2 
Remote-FTP 0.9.4 
seti-ui 1.3.1 
vim-mode 0.65.1 
webbox-color 0.5.9 
```

**Comment by Bonjew** [comment]
I got the same problem.

**Comment by thomaslindstrom** [comment]
Please update `color-picker`. The newest version is `v2.2.5`.

**Comment by Bonjew** [comment]
Problem has been solved while the newest version installed. The new version downloaded separately from the old version, so I deleted the old version and restarted the Atom. Then it works.

**Comment by cristian1913** [comment]
Sólo tienen que actualizar la versión color-picker y listo. Ya se arregla este problema con atom.

**Comment by huysh3** [comment]
Solved.
Thank you, and happy coding : )

**Comment by Gaohaoyang** [comment]
#214

**Comment by philharmonie** [comment]
Have the same issue with 2.2.5 even after delete and reinstall
