### ISSUE TITLE
Uncaught TypeError: Cursor.getPixelRect is not a function

### ISSUE THREAD

**Issue by Gaohaoyang** [thomaslindstrom/color-picker#214]
```
/Users/haoyanggao/.atom/packages/color-picker/lib/ColorPicker-view.coffee:365
```

```
TypeError: Cursor.getPixelRect is not a function
    at Object.open (/Users/haoyanggao/.atom/packages/color-picker/lib/ColorPicker-view.coffee:365:42)
    at atom-text-editor.<anonymous> (/Users/haoyanggao/.atom/packages/color-picker/lib/ColorPicker.coffee:47:23)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

- Atom 1.15.0 x64
- macOS 10.12.3

**Comment by Gaohaoyang** [comment]
#213

**Comment by ZhangMingZhao1** [comment]
How solve it???!!!
