### ISSUE TITLE
error

### ISSUE THREAD

**Issue by afirisaza** [thomaslindstrom/color-picker#219]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package 2.2.5

### Stack Trace

Uncaught TypeError: Cursor.getPixelRect is not a function

```
At /C:/Users/User/.atom/packages/color-picker/lib/ColorPicker-view.coffee:351

TypeError: Cursor.getPixelRect is not a function
    at Object.open (/packages/color-picker/lib/ColorPicker-view.coffee:302:42)
    at /packages/color-picker/lib/ColorPicker.coffee:47:23)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -4:55.3.0 settings-view:open (input.hidden-input)
     -4:18.8.0 color-picker:open (input.hidden-input)
     -3:14.1.0 core:backspace (input.hidden-input)
     -3:12.4.0 core:confirm (input.hidden-input)
     -0:08.1.0 color-picker:open (input.hidden-input)
```

### Non-Core Packages

```
color-picker 2.2.5 
emmet 2.4.3 
file-icons 1.7.25 
fonts 1.8.0 
linter 1.11.18 
minimap 4.26.4 
```

**Comment by afirisaza** [comment]
me genera error
