### ISSUE TITLE
Can not install color-picker on Atom 1.26.1 x64

### ISSUE THREAD

**Issue by taobo33** [thomaslindstrom/color-picker#238]
Tried to install from package menu and failed again and again. The failed output are as below:
```
Installing “color-picker@2.3.0” failed.Hide output…

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.7.11/iojs-v1.7.11.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: connect ETIMEDOUT 52.216.65.232:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1022:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1045:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\taobo\\AppData\\Local\\atom\\app-1.26.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\taobo\\AppData\\Local\\atom\\app-1.26.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=1.7.11" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd C:\Users\taobo\.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

Compiler tools not found
Packages that depend on modules that contain C/C++ code will fail to install.
Read here for instructions on installing Python and Visual Studio.
Run apm install --check after installing to test compiling a native module.
```

Then I ran "apm install --check" in windows power shell and got the following:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.7.11/iojs-v1.7.11.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: connect ETIMEDOUT 52.216.65.16:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1022:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1045:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\taobo\\AppData\\Local\\atom\\app-1.26.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\taobo\\AppData\\Local\\atom\\app-1.26.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=1.7.11" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd C:\Users\taobo\.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

Thanks for checking out on this.

**Comment by taobo33** [comment]
Solved it, might have something to do with the new Windows 10 1803 update, I can install color-picker now after a fix on registry(The new update create unknown user which does not have the privilege for internet access it seems )
