### ISSUE TITLE
Installing color-picker failed

### ISSUE THREAD

**Issue by mmchel12** [thomaslindstrom/color-picker#241]
Whenever I try installing this, or any other package, this is what comes up:

Installing “color-picker@2.3.0” failed.

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | darwin | x64
gyp http GET https://atom.io/download/electron/v2.0.4/iojs-v2.0.4.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
gyp ERR! stack     at emitNone (events.js:86:13)
gyp ERR! stack     at TLSSocket.emit (events.js:185:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:603:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/private/var/folders/8r/8n4j2jfn56x40y5yq_6msqdm0000gn/T/AppTranslocation/2F28CFCC-BD1F-4FF3-95A6-3324FCB6317D/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/8r/8n4j2jfn56x40y5yq_6msqdm0000gn/T/AppTranslocation/2F28CFCC-BD1F-4FF3-95A6-3324FCB6317D/d/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=2.0.4" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/Michelle/.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

What should I do? It's driving me crazy.
My atom version is 1.28.1 on a mac OS Sierra

**Comment by tye-shutty** [comment]
I can install other packages, but not this one. 
Atom version: 1.39.1 x64 Computer: macOS Mojave 10.14.5
This color picker works for OS X: https://github.com/gregerolsson/native-color-picker

0 info it worked if it ends with ok
1 verbose cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
1 verbose cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/Users/tshutty/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/Users/tshutty/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/an-color-picker/versions/1.0.2/tarball',
1 verbose cli   '--runtime=electron',
1 verbose cli   '--target=3.1.10',
1 verbose cli   '--dist-url=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v8.9.3
4 verbose npm-session f937118a84506701
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 400 https://www.atom.io/api/packages/an-color-picker/versions/1.0.2/tarball 385ms
8 silly fetchPackageMetaData error for https://www.atom.io/api/packages/an-color-picker/versions/1.0.2/tarball 400 Bad Request: https://www.atom.io/api/packages/an-color-picker/versions/1.0.2/tarball
9 timing stage:rollbackFailedOptional Completed in 3ms
10 timing stage:runTopLevelLifecycles Completed in 538ms
11 verbose stack Error: 400 Bad Request: https://www.atom.io/api/packages/an-color-picker/versions/1.0.2/tarball
11 verbose stack     at fetch.then.res (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
11 verbose stack     at tryCatcher (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
11 verbose stack     at Promise._settlePromise (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
11 verbose stack     at Async._drainQueue (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
11 verbose stack     at Async._drainQueues (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
11 verbose stack     at runCallback (timers.js:789:20)
11 verbose stack     at tryOnImmediate (timers.js:751:5)
11 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
12 verbose cwd /private/var/folders/n1/h5y3tbd13731m4x6vxlwxpdc0000gp/T/apm-install-dir-119630-4412-253x81.f5c1xj
13 verbose Darwin 18.6.0
14 verbose argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/tshutty/.atom/.apm/.apmrc" "--userconfig" "/Users/tshutty/.atom/.apmrc" "install" "https://www.atom.io/api/packages/an-color-picker/versions/1.0.2/tarball" "--runtime=electron" "--target=3.1.10" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style"
15 verbose node v8.9.3
16 verbose npm  v6.2.0
17 error code E400
18 error 400 Bad Request: https://www.atom.io/api/packages/an-color-picker/versions/1.0.2/tarball
19 verbose exit [ 1, true ]
