### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by dfabreguette-ap** [thomaslindstrom/color-picker#60]
Just used the color picker normally, right click on hexa color code and select "color picker".

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v1.4.4

### Stack Trace

Uncaught TypeError: Cannot read property 'querySelector' of null

```
At /Users/davidfabreguette/.atom/packages/color-picker/lib/ColorPicker-view.coffee:101

TypeError: Cannot read property 'querySelector' of null
  at ColorPickerView.module.exports.ColorPickerView.open (/Users/davidfabreguette/.atom/packages/color-picker/lib/ColorPicker-view.coffee:101:66)
  at Object.module.exports.open (/Users/davidfabreguette/.atom/packages/color-picker/lib/ColorPicker.coffee:108:23)
  at atom-text-editor.atom.commands.add.color-picker:open (/Users/davidfabreguette/.atom/packages/color-picker/lib/ColorPicker.coffee:20:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/davidfabreguette/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Users/davidfabreguette/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/davidfabreguette/Downloads/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Users/davidfabreguette/Downloads/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at Ipc.<anonymous> (/Users/davidfabreguette/Downloads/Atom.app/Contents/Resources/app/src/window-event-handler.js:70:67)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Users/davidfabreguette/Downloads/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)
  at Ipc.sendSync (/Users/davidfabreguette/Downloads/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:39:29)
  at Ipc.sendChannelSync (/Users/davidfabreguette/Downloads/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:47:28)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Users/davidfabreguette/Downloads/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Users/davidfabreguette/Downloads/Atom.app/Contents/Resources/app/src/context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (/Users/davidfabreguette/Downloads/Atom.app/Contents/Resources/app/src/window-event-handler.js:138:33)
  at HTMLDocument.handler (/Users/davidfabreguette/Downloads/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Users/davidfabreguette/Downloads/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Users/davidfabreguette/Downloads/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -0:00.0 pane:show-previous-item (input.hidden-input)
```

### Config

```
{
  "core": {
    "disabledPackages": [
      "atom-color-highlight"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
language-haml, v0.15.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by thomaslindstrom** [comment]
Hi! Please update `Atom` and try again.
