### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by kamilahjae** [thomaslindstrom/color-picker#61]
Uncaught TypeError: Cannot read property '0' of undefined

**Atom Version**: 0.155.0
**System**: Mac OS X 10.10.1
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v1.2.1

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Users/kamilahjenkins/.atom/packages/color-picker/lib/ColorPicker-view.coffee:99

TypeError: Cannot read property '0' of undefined
  at ColorPickerView.module.exports.ColorPickerView.open (/Users/kamilahjenkins/.atom/packages/color-picker/lib/ColorPicker-view.coffee:99:38)
  at Object.module.exports.open (/Users/kamilahjenkins/.atom/packages/color-picker/lib/ColorPicker.coffee:102:23)
  at atom-workspace.<anonymous> (/Users/kamilahjenkins/.atom/packages/color-picker/lib/ColorPicker.coffee:19:69)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:70:67)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)
  at Ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:39:29)
  at Ipc.sendChannelSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:47:28)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:138:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

/cc @atom/core

**Comment by thomaslindstrom** [comment]
Hi! Please update both `Atom` and the `color-picker` package and try again.
