### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by alphyon** [thomaslindstrom/color-picker#62]
Uncaught TypeError: Cannot read property 'querySelector' of null

**Atom Version**: 0.162.0
**System**: linux 3.16.0-4-amd64
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v1.4.4

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /home/alphyon/.atom/packages/color-picker/lib/ColorPicker-view.coffee:101

TypeError: Cannot read property 'querySelector' of null
  at ColorPickerView.module.exports.ColorPickerView.open (/home/alphyon/.atom/packages/color-picker/lib/ColorPicker-view.coffee:101:66)
  at Object.module.exports.open (/home/alphyon/.atom/packages/color-picker/lib/ColorPicker.coffee:108:23)
  at atom-text-editor.atom.commands.add.color-picker:open (/home/alphyon/.atom/packages/color-picker/lib/ColorPicker.coffee:20:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by thomaslindstrom** [comment]
Hi. Please update `Atom` and try again. Thanks!

**Comment by alphyon** [comment]
Thanks it is solved my problem
