### ISSUE TITLE
Failed to activate the color-picker package

### ISSUE THREAD

**Issue by mannaxc** [thomaslindstrom/color-picker#68]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v1.4.4

### Stack Trace

Failed to activate the color-picker package

```
At Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('FF0000') could not be parsed as a color.

Error: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('FF0000') could not be parsed as a color.
    at Error (native)
    at Object.module.exports.render (/Users/paullyd/.atom/packages/color-picker/lib/ColorPicker-hueSelector.coffee:29:19)
    at ColorPickerView.module.exports.ColorPickerView.initialize (/Users/paullyd/.atom/packages/color-picker/lib/ColorPicker-view.coffee:125:19)
    at ColorPickerView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:145:25)
    at new ColorPickerView (/Users/paullyd/.atom/packages/color-picker/lib/ColorPicker-view.coffee:22:52)
    at Object.module.exports.activate (/Users/paullyd/.atom/packages/color-picker/lib/ColorPicker.coffee:33:26)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
```

### Commands

```
     -0:14.8 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
monokai, v0.7.0

# Dev
No dev packages
```

**Comment by bshyong** [comment]
+1 just got this error too

**Comment by thomaslindstrom** [comment]
Hi, @mannaxc and @bshyong. Please try upgrading to `color-picker v.1.5.0` and try again.

**Comment by melitta** [comment]
+1

**Comment by liujiaqiid** [comment]
I fixed this error by updated to color-picker 1.7 + atom 0.196

**Comment by vgrbr** [comment]
Fixed with updating color-picker too with latest atom..

**Comment by thomaslindstrom** [comment]
This should be fixed in the upcoming `v2.0.0`.

**Comment by maskedcoder** [comment]
[Enter steps to reproduce below:]

1. Start Atom
2. Wait for the error to pop up as the packages are loaded

**Atom Version**: 1.0.19
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v2.1.1


### Stack Trace

Failed to activate the color-picker package

```
At _editorView.onDidChangeScrollTop is not a function

TypeError: _editorView.onDidChangeScrollTop is not a function
    at C:\Users\...\.atom\packages\color-picker\lib\ColorPicker-view.coffee:122:48
    at Workspace.module.exports.Workspace.observeTextEditors (C:\Users\...\AppData\Local\atom\app-1.0.19\resources\app.asar\src\workspace.js:276:9)
    at Object.activate (C:\Users\...\.atom\packages\color-picker\lib\ColorPicker-view.coffee:120:28)
    at Object.module.exports.activate (C:\Users\...\.atom\packages\color-picker\lib\ColorPicker.coffee:50:26)
    at Package.module.exports.Package.activateNow (C:\Users\...\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:245:19)
    at C:\Users\...\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:226:30
    at Package.module.exports.Package.measure (C:\Users\...\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:169:15)
    at Package.module.exports.Package.activate (C:\Users\...\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:218:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\...\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:486:21)
    at C:\Users\...\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:469:29
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
blackspace, v1.1.0
color-picker, v2.1.1
docs-snippets, v0.8.0
emmet, v2.4.1
file-icons, v1.6.15
indent-guide-improved, v1.4.4
language-ejs, v0.2.0
linter-rails-best-practices, v0.2.2
pigments, v0.24.1

# Dev
No dev packages
```

---

@thomaslindstrom Would you like me to open a separate issue for this?

**Comment by zhuanghaixin** [comment]
# Failed to activate the color-picker package
## EPERM: operation not permitted, open 'C:\Users\zhuan\.atom\compile-cache\coffee\e29df72936776f6faee9b5ed0526144a37398a10.js'
### Error: EPERM: operation not permitted, open 'C:\Users\zhuan\.atom\compile-cache\coffee\e29df72936776f6faee9b5ed0526144a37398a10.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Proxy.writeFileSync (C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\node_modules\fs-plus\lib\fs-plus.js:298:29)
    at writeCachedJavascript (C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\src\compile-cache.js:117:12)
    at compileFileAtPath (C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\src\compile-cache.js:98:13)
    at Object.value [as .coffee] (C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\src\compile-cache.js:238:26)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///C:/Users/zhuan/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\src\native-compile-cache.js:66:33)
    at module.exports (file:///C:/Users/zhuan/.atom/packages/color-picker/lib/ColorPicker-view.coffee:8:22)
    at Object.activate (file:///C:/Users/zhuan/.atom/packages/color-picker/lib/ColorPicker.coffee:9:21)
    at Package.module.exports.Package.activateNow (C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\src\package.js:253:25)
    at C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\src\package.js:225:38
    at Package.module.exports.Package.measure (C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\src\package.js:99:21)
    at C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\src\package.js:218:32
    at Package.module.exports.Package.activate (C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\src\package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\src\package-manager.js:645:40)
    at C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\src\package-manager.js:377:25
    at C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\src\config.js:644:26
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\src\config.js:835:35)
    at Config.module.exports.Config.setRawValue (C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\src\config.js:621:25)
    at Config.module.exports.Config.set (C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\src\config.js:236:20)
    at Config.module.exports.Config.removeAtKeyPath (C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\src\config.js:386:18)
    at Package.module.exports.Package.enable (C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\src\package.js:84:32)
    at PackageManager.module.exports.PackageManager.enablePackage (C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\src\package-manager.js:188:20)
    at HTMLButtonElement.enablementButtonClickHandler (C:\Users\zhuan\AppData\Local\atom\app-1.18.0\resources\app\node_modules\settings-view\lib\package-card.js:361:31)
