### ISSUE TITLE
Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by thiagolucio** [thomaslindstrom/color-picker#71]
**Atom Version**: 0.188.0
**System**: Windows Seven Pró/ Windows 8
**Thrown From**: [color-picker -  package, v1.5.0

### Stack Trace
At Cannot find module 'atom-space-pen-views'
Failed to activate the color-picker package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (C:\Users\thiago.silva\AppData\Local\atom\app-0.188.0\resources\app\src\module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (C:\Users\thiago.silva\.atom\packages\color-picker\lib\ColorPicker-view.coffee:5:14)
  at Object.<anonymous> (C:\Users\thiago.silva\.atom\packages\color-picker\lib\ColorPicker-view.coffee:5:5)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (C:\Users\thiago.silva\AppData\Local\atom\app-0.188.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.module.exports.activate (C:\Users\thiago.silva\.atom\packages\color-picker\lib\ColorPicker.coffee:29:37)
  at Package.module.exports.Package.activateNow (C:\Users\thiago.silva\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:240:19)
  at C:\Users\thiago.silva\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:221:30
  at Package.module.exports.Package.measure (C:\Users\thiago.silva\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.activate (C:\Users\thiago.silva\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\thiago.silva\AppData\Local\atom\app-0.188.0\resources\app\src\package-manager.js:461:21)
  at C:\Users\thiago.silva\AppData\Local\atom\app-0.188.0\resources\app\src\package-manager.js:445:29
  at Config.module.exports.Config.transact (C:\Users\thiago.silva\AppData\Local\atom\app-0.188.0\resources\app\src\config.js:343:16)
  at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\thiago.silva\AppData\Local\atom\app-0.188.0\resources\app\src\package-manager.js:440:19)
  at PackageManager.module.exports.PackageManager.activate (C:\Users\thiago.silva\AppData\Local\atom\app-0.188.0\resources\app\src\package-manager.js:423:46)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\thiago.silva\AppData\Local\atom\app-0.188.0\resources\app\src\atom.js:625:21)
  at Object.<anonymous> (C:\Users\thiago.silva\AppData\Local\atom\app-0.188.0\resources\app\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\thiago.silva\AppData\Local\atom\app-0.188.0\resources\app\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (C:\Users\thiago.silva\AppData\Local\atom\app-0.188.0\resources\app\src\babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at window.onload (file:///C:/Users/thiago.silva/AppData/Local/atom/app-0.188.0/resources/app/static/index.js:51:25)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-plus-async",
      "atom-beautify"
    ],
    "themes": [
      "seti-ui",
      "monokai"
    ],
    "followSymlinks": true
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
autocomplete-paths, v1.0.2
color-picker, v1.5.0
minimap, v4.6.0
monokai, v0.12.0
open-last-project, v0.3.5
reveal-active-file-context, v0.2.0
run-in-browser, v0.1.3
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by thomaslindstrom** [comment]
Please try uninstalling and installing `color-picker`, then try again.
