### ISSUE TITLE
Uncaught TypeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': float parameter 1 is non-finite.

### ISSUE THREAD

**Issue by SolusSoftworks** [thomaslindstrom/color-picker#73]
Opened the color picker on a HSLA value.

**Atom Version**: 0.187.0
**System**: linux 3.16.0-31-generic
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v1.5.0

### Stack Trace

Uncaught TypeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': float parameter 1 is non-finite.

```
At /home/james/.atom/packages/color-picker/lib/ColorPicker-saturationSelector.coffee:55

TypeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': float parameter 1 is non-finite.
  at TypeError (native)
  at Object.getColorAtPosition (/home/james/.atom/packages/color-picker/lib/ColorPicker-saturationSelector.coffee:55:35)
  at ColorPickerView.module.exports.ColorPickerView.refreshAlphaCanvas (/home/james/.atom/packages/color-picker/lib/ColorPicker-view.coffee:361:41)
  at ColorPickerView.module.exports.ColorPickerView.inputColor (/home/james/.atom/packages/color-picker/lib/ColorPicker-view.coffee:487:14)
  at Object.module.exports.setMatchColor (/home/james/.atom/packages/color-picker/lib/ColorPicker.coffee:122:27)
  at /home/james/.atom/packages/color-picker/lib/ColorPicker.coffee:125:33
  at /home/james/.atom/packages/color-picker/lib/ColorPicker.coffee:130:61
  at Object.module.exports.setMatchColor (/home/james/.atom/packages/color-picker/lib/ColorPicker.coffee:130:26)
  at Object.module.exports.open (/home/james/.atom/packages/color-picker/lib/ColorPicker.coffee:107:18)
  at atom-text-editor.atom.commands.add.color-picker:open (/home/james/.atom/packages/color-picker/lib/ColorPicker.coffee:20:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:246:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:159:19)
  at [object Object].jQuery.fn.trigger (/usr/share/atom/resources/app/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:80:67)
  at EventEmitter.emit (events.js:119:17)
  at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app/src/context-menu-manager.js:172:33)
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:153:33)
  at HTMLDocument.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -9:54.1 core:save (atom-text-editor.editor.is-focused)
  3x -9:43.0 core:move-left (atom-text-editor.editor.is-focused)
     -9:42.3 core:backspace (atom-text-editor.editor.is-focused)
     -9:36.3 core:save (atom-text-editor.editor.is-focused)
     -1:10.5 editor:newline (atom-text-editor.editor.is-focused)
     -1:08.9 autocomplete-plus:select-next (atom-text-editor.editor.is-focused)
  2x -1:08.6 autocomplete-plus:confirm (atom-text-editor.editor.is-focused)
  3x -1:03.4 core:move-left (atom-text-editor.editor.is-focused)
     -1:02.2 core:paste (atom-text-editor.editor.is-focused)
     -1:00.5 core:save (atom-text-editor.editor.is-focused)
     -0:58.8 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  3x -0:38.5 core:backspace (atom-text-editor.editor.is-focused)
     -0:31.1 core:move-left (atom-text-editor.editor.is-focused)
     -0:29.7 color-picker:open (atom-text-editor.editor.is-focused)
  7x -0:21.9 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
auto-indent, v0.1.0
autoclose-html, v0.15.0
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.6.0
color-picker, v1.5.0
minimap, v4.6.0

# Dev
No dev packages
```

**Comment by thomaslindstrom** [comment]
Hi, could you please send me the HSLA value you were trying to open?

**Comment by dubert** [comment]
This hsla produces this error: `hsla(0, 0%, 0%, 0.42)`

**Comment by thomaslindstrom** [comment]
`hsla(0, 0%, 0%, 0.42)` works in the upcoming `v2.0.0`.
