### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by shahsayyad** [thomaslindstrom/color-picker#74]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.2
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package, v1.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'type' of null

```
At /Users/Sayyad/.atom/packages/color-picker/lib/ColorPicker-view.coffee:383

TypeError: Cannot read property 'type' of null
  at ColorPickerView.module.exports.ColorPickerView.refreshColor (/Users/Sayyad/.atom/packages/color-picker/lib/ColorPicker-view.coffee:383:60)
  at HTMLBodyElement.<anonymous> (/Users/Sayyad/.atom/packages/color-picker/lib/ColorPicker-view.coffee:215:29)
  at HTMLBodyElement.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLBodyElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLBodyElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -38:07.1 core:confirm (input.hidden-input)
     -30:00.0 core:cancel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-atom-dark-ui)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.1.3
color-picker, v1.5.0
css-snippets, v0.5.0
emmet, v2.3.4
linter, v0.10.1
seti-syntax, v0.2.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by thomaslindstrom** [comment]
Hi, please update `Atom` and try again.

**Comment by shahsayyad** [comment]
ok thanks
